### ISSUE TITLE
Bigger input image sizes

### ISSUE THREAD

**Issue by rmbarbosa** [Coderx7/SimpNet#2]
Hello, first of all very nice work.

Could you explain how can i use this simpnet in bigger images like 256x256 ou similar because if i change the input layer to this size it creates an out of memory.

Thank you.

**Comment by Coderx7** [comment]
Hi @rmbarbosa ,
The architecture that you see in the github repo is designed specifically for CIFAR10/100 datasets and the likes.(small input sizes).
For larger inputs, such as the ones used in imagenet(such as 256x256 or 224x224 and the likes), the architecture needs to be altered in a way that the input image does not cause an out of memory issue(the featuremaps would get very big becasue of the usage of stride of 1 everywhere), therefore usually in the early layers bigger strides are used.
I'm currently training one configuration on ImageNet and when its done I will upload the model.
If you want to have a quick test yourself you may use one of the basic (early) configs.
please note that the optimal config will be announced after the training procedures are finished since there is a lot going on under the hood which affects the network performance and accuracy(hopefully I'll explain this in the new revision). 
For the time being use stride of 2 for the first 3 layers and you should be good to go.

**Comment by rmbarbosa** [comment]
Hello @Coderx7 ,
Thank you very much for your answer.

I've tried the procedures you've said and actually the stride was causing the out of memory, and when i've set the stride to 2 in the first 3 layers it started to process.
But it never converges and the network is not learnig nothing, so its not working and i think more changes are needed.
So can you provide at least some non-optimal :-) config so that i can try?
i have a nice GPU rig and if you want i could test some configs for you.
Best regards.

**Comment by Coderx7** [comment]
@rmbarbosa : Thats very unlickly to be caused by the network itself you need to dig deeper to find out what is causing such issue.
The config I gave you earlier was indeed one of the first configs to be tested and it achieved 68+ Top 1 on ImageNet (with the same optimization policy mobilenet achieved 66 top1), Clearly the optimization policy still needs a lot of improvement, however, achieving that accuracy alone proves the network is fine.

I uploaded the first and second configs for you to test it on your own, here you are : 
[simpnet_imgnet_5m_testConfig.zip](https://github.com/Coderx7/SimpNet/files/2455917/simpnet_imgnet_5m_testConfig.zip)

 You should be able to use them without any issues.
